services:
  db:
    image: postgres:16
    container_name: autoria-db
    restart: always
    environment:
      POSTGRES_USER: autoria
      POSTGRES_PASSWORD: autoria
      POSTGRES_DB: autoria
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autoria-network

  autoriaparser:
    build: .
    container_name: autoriaparser-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+pg8000://autoria:autoria@db:5435/autoria
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local

networks:
  autoria-network:
    driver: bridge