version: '3.9'

services:
  db:
    image: postgres:16
    container_name: autoria_db
    restart: always
    environment:
      POSTGRES_USER: autoria_user
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: autoria_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  autoriaParser:
    build: .
    container_name: autoriaParser_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://autoria_user:strongpassword@db:5432/autoria_db
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
